import { Rating } from "./Rating";
export { Rating } from "./Rating";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { apiClient, get } from "../../api/client";
import { ErrorState, Field, Loading, Pagination, TripCard } from "../../components/ui";
import { useAuth } from "../auth/AuthProvider";
import { canManageOperator } from "../auth/access";
import type { PagedResponse } from "../../types/api";
import type { Named, Trip } from "../../types/customer";
import { dateTime } from "../../utils/format";
import "./marketplace.css";

export interface PublicOperator extends Named { description: string | null; logoUrl: string | null; averageRating: number | null; reviewCount: number }
interface Review { id: number; rating: number; text: string; customerName: string; operatorId: number; operatorName: string; routeName: string; createdAt: string; updatedAt: string; response: string | null; responseUpdatedAt: string | null }
interface Route extends Named { pickupLocationId: number; dropoffLocationId: number }
interface Profile { operator: PublicOperator; routes: Route[]; busTypes: Named[]; trips: Trip[] }
interface Eligibility { eligible: boolean; reason: string | null; review: Review | null }
const paged = async <T,>(path: string, page = 0, size = 10, signal?: AbortSignal) => (await apiClient.get<PagedResponse<T>>(path, { params: { page, size }, signal })).data;
function ReviewCard({ review, children }: { review: Review; children?: React.ReactNode }) {
  return <article className="card marketplace-review"><div className="split"><strong>{review.customerName}</strong><span aria-label={`${review.rating} trên 5 sao`}>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span></div><p className="muted">{review.routeName} · {dateTime(review.createdAt)}</p><p className="review-text">{review.text}</p>{review.response && <blockquote><strong>Phản hồi từ {review.operatorName}</strong><p className="review-text">{review.response}</p></blockquote>}{children}</article>;
}
export function HomeDiscovery() {
  const operators = useQuery({ queryKey: ["marketplace", "operators"], queryFn: ({signal}) => paged<PublicOperator>("/public/discovery/operators",0,6,signal) });
  const routes = useQuery({ queryKey: ["marketplace", "routes"], queryFn: ({signal}) => get<Route[]>("/public/discovery/routes",undefined,signal) });
  const upcoming = useQuery({ queryKey: ["marketplace", "upcoming"], queryFn: ({signal}) => get<Trip[]>("/public/discovery/trips",undefined,signal) });
  const reviews = useQuery({ queryKey: ["marketplace", "recent"], queryFn: ({signal}) => paged<Review>("/public/reviews/recent",0,4,signal) });
  return <div className="marketplace"><section><h2>Khám phá nhà xe</h2><p className="muted">Nhà xe đang hoạt động, ưu tiên đánh giá từ khách đã đi.</p>{operators.isPending ? <Loading /> : operators.isError ? <ErrorState error={operators.error} retry={()=>operators.refetch()} /> : <div className="market-grid">{operators.data.data.length ? operators.data.data.map(op=><Link className="card market-operator" key={op.id} to={`/operators/${op.id}`}><h3>{op.name}</h3><Rating {...op} /></Link>) : <p>Chưa có nhà xe đang hoạt động.</p>}</div>}</section><section><h2>Tuyến đang hoạt động</h2>{routes.isPending ? <Loading /> : routes.isError ? <ErrorState error={routes.error} retry={()=>routes.refetch()} /> : <div className="market-grid">{routes.data.length ? routes.data.map(r=><Link className="card" key={r.id} to={`/search?pickupLocationId=${r.pickupLocationId}&dropoffLocationId=${r.dropoffLocationId}&departureDate=${new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date())}`}>{r.name}</Link>) : <p>Chưa có tuyến đang hoạt động.</p>}</div>}</section><section><h2>Chuyến sắp khởi hành</h2><p className="muted">Chuyến còn chỗ trong 30 ngày tới. Kiểm tra điểm đón, điểm trả trước khi chọn.</p>{upcoming.isPending ? <Loading /> : upcoming.isError ? <ErrorState error={upcoming.error} retry={()=>upcoming.refetch()} /> : upcoming.data.length ? upcoming.data.map(t=><TripCard key={t.tripId} trip={t} />) : <p>Chưa có chuyến khả dụng trong thời gian này.</p>}</section><section><h2>Đánh giá gần đây</h2>{reviews.isPending ? <Loading /> : reviews.isError ? <ErrorState error={reviews.error} retry={()=>reviews.refetch()} /> : reviews.data.data.length ? <div className="market-grid">{reviews.data.data.map(r=><div key={r.id}><Link to={`/operators/${r.operatorId}`}>{r.operatorName}</Link><ReviewCard review={r} /></div>)}</div> : <p>Chưa có đánh giá từ khách đã hoàn thành hành trình.</p>}</section></div>;
}
export function OperatorProfilePage() {
  const {operatorId}=useParams(); const [page,setPage]=useState(0);
  const profile=useQuery({queryKey:["marketplace","profile",operatorId],queryFn:({signal})=>get<Profile>(`/public/operators/${operatorId}/profile`,undefined,signal)});
  const reviews=useQuery({queryKey:["marketplace","reviews",operatorId,page],queryFn:({signal})=>paged<Review>(`/public/operators/${operatorId}/reviews`,page,10,signal)});
  if(profile.isPending) return <Loading />; if(profile.isError) return <ErrorState error={profile.error} retry={()=>profile.refetch()} />;
  const p=profile.data;
  return <div className="marketplace"><Link to="/">← Trang chủ</Link><section className="card"><div className="market-profile-heading">{p.operator.logoUrl && <img src={p.operator.logoUrl} alt={`Logo ${p.operator.name}`} onError={e=>{e.currentTarget.hidden=true;}} />}<div><h1>{p.operator.name}</h1><Rating {...p.operator} /></div></div><p className="review-text">{p.operator.description || "Nhà xe chưa cập nhật giới thiệu công khai."}</p><h2>Tuyến vận hành</h2><ul>{p.routes.map(r=><li key={r.id}>{r.name}</li>)}</ul>{!p.routes.length && <p>Chưa có tuyến hoạt động.</p>}<h2>Loại xe</h2><p>{p.busTypes.map(t=>t.name).join(" · ") || "Chưa có loại xe khả dụng."}</p></section><section><h2>Chuyến sắp khởi hành</h2><p className="muted">Trong 30 ngày tới · Chỗ trống được kiểm tra lại khi đặt vé.</p>{p.trips.length ? p.trips.map(t=><TripCard key={t.tripId} trip={t} />) : <p>Chưa có chuyến khả dụng trong thời gian này.</p>}</section><section><h2>Đánh giá từ khách đã đi</h2>{reviews.isPending ? <Loading /> : reviews.isError ? <ErrorState error={reviews.error} retry={()=>reviews.refetch()} /> : <>{reviews.data.data.length ? reviews.data.data.map(r=><ReviewCard key={r.id} review={r} />) : <p>Chưa có đánh giá</p>}<Pagination pagination={reviews.data.pagination} onPage={setPage} /></>}</section></div>;
}
function ReviewForm({bookingId,review,canCreate}:{bookingId:number;review:Review|null;canCreate:boolean}) {
  const cache=useQueryClient(); const [rating,setRating]=useState(review?.rating ?? 5); const [text,setText]=useState(review?.text ?? ""); const [saved,setSaved]=useState(false); const [confirmDelete,setConfirmDelete]=useState(false);
  const mutation=useMutation({mutationFn:async(action:"save"|"delete")=> action==="delete" ? apiClient.delete(`/bookings/${bookingId}/review`) : apiClient.request({url:`/bookings/${bookingId}/review`,method:review?"PUT":"POST",data:{rating,text}}),onSuccess:async()=>{setSaved(true); await cache.invalidateQueries({queryKey:["marketplace"]}); await cache.invalidateQueries({queryKey:["search"]});}});
  return <>{review && <ReviewCard review={review} />}{(canCreate || review) && <form className="form-stack" onSubmit={e=>{e.preventDefault();mutation.mutate("save");}}><label className="field">Số sao<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(v=><option key={v} value={v}>{v} sao</option>)}</select></label><label className="field">Nhận xét<textarea required maxLength={2000} value={text} onChange={e=>setText(e.target.value)} /></label><div className="market-actions"><button disabled={mutation.isPending || !text.trim()}>{review ? "Lưu đánh giá" : "Gửi đánh giá"}</button>{review && <button type="button" className="secondary" disabled={mutation.isPending} onClick={()=>setConfirmDelete(true)}>Xóa đánh giá</button>}</div>{confirmDelete && <div className="notice" role="alert"><p>Ẩn đánh giá này khỏi trang công khai?</p><div className="market-actions"><button type="button" disabled={mutation.isPending} onClick={()=>mutation.mutate("delete")}>Xác nhận xóa đánh giá</button><button type="button" className="secondary" onClick={()=>setConfirmDelete(false)}>Giữ đánh giá</button></div></div>}</form>}{mutation.isError && <ErrorState error={mutation.error} />}{saved && <p role="status">Đã cập nhật đánh giá.</p>}</>;
}
export function BookingReviewSection({bookingId}:{bookingId:number}) {
  const auth=useAuth(); const query=useQuery({queryKey:["marketplace","eligibility",auth.user?.id,bookingId],queryFn:({signal})=>get<Eligibility>(`/bookings/${bookingId}/review-eligibility`,undefined,signal)});
  return <section className="card marketplace"><h2>Đánh giá hành trình</h2>{query.isPending ? <Loading /> : query.isError ? <ErrorState error={query.error} retry={()=>query.refetch()} /> : <>{!query.data.eligible && !query.data.review && <p>Đánh giá dành cho vé được giữ lại có chỗ chưa hủy sau khi chuyến hoàn thành.</p>}<ReviewForm key={query.data.review?.updatedAt || "new"} bookingId={bookingId} review={query.data.review} canCreate={query.data.eligible} /></>}</section>;
}
function ResponseForm({review}:{review:Review}) {
  const cache=useQueryClient(); const [text,setText]=useState(review.response || ""); const mutation=useMutation({mutationFn:()=>apiClient.put(`/operator/reviews/${review.id}/response`,{text}),onSuccess:()=>cache.invalidateQueries({queryKey:["marketplace"]})});
  return <form className="form-stack" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><label className="field">Phản hồi công khai<textarea required maxLength={2000} value={text} onChange={e=>setText(e.target.value)} /></label><button disabled={mutation.isPending || !text.trim()}>{review.response ? "Lưu phản hồi" : "Gửi phản hồi"}</button>{mutation.isError && <ErrorState error={mutation.error} />}{mutation.isSuccess && <p role="status">Đã lưu phản hồi.</p>}</form>;
}
function ProfileForm({profile}:{profile:PublicOperator}) {
  const cache=useQueryClient(); const [description,setDescription]=useState(profile.description || ""); const [logoUrl,setLogoUrl]=useState(profile.logoUrl || ""); const mutation=useMutation({mutationFn:()=>apiClient.put("/operator/marketplace-profile",{description,logoUrl}),onSuccess:()=>cache.invalidateQueries({queryKey:["marketplace"]})});
  return <form className="form-stack" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><h2>Hồ sơ công khai</h2><label className="field">Giới thiệu nhà xe<textarea maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} /></label><Field label="URL logo (HTTPS hoặc đường dẫn nội bộ)" maxLength={500} value={logoUrl} onChange={e=>setLogoUrl(e.target.value)} /><button disabled={mutation.isPending}>Lưu hồ sơ công khai</button>{mutation.isError && <ErrorState error={mutation.error} />}{mutation.isSuccess && <p role="status">Đã lưu hồ sơ.</p>}</form>;
}
export function OperatorReviewsPage() {
  const auth=useAuth(); const admin=canManageOperator(auth.user?.roles); const [page,setPage]=useState(0);
  const profile=useQuery({queryKey:["marketplace","own-profile",auth.user?.id],queryFn:({signal})=>get<PublicOperator>("/operator/marketplace-profile",undefined,signal)});
  const reviews=useQuery({queryKey:["marketplace","own-reviews",auth.user?.id,page],queryFn:({signal})=>paged<Review>("/operator/reviews",page,10,signal)});
  return <div className="marketplace"><h1>Hồ sơ và đánh giá</h1>{profile.isPending ? <Loading /> : profile.isError ? <ErrorState error={profile.error} retry={()=>profile.refetch()} /> : <section className="card"><h2>{profile.data.name}</h2><Rating {...profile.data} /><p><Link to={`/operators/${profile.data.id}`}>Xem trang công khai</Link></p>{admin ? <ProfileForm key={profile.data.id} profile={profile.data} /> : <p>{profile.data.description || "Chưa có giới thiệu công khai."}</p>}</section>}<section><h2>Đánh giá của khách</h2>{!admin && <p className="muted">Nhân viên có quyền xem đánh giá.</p>}{reviews.isPending ? <Loading /> : reviews.isError ? <ErrorState error={reviews.error} retry={()=>reviews.refetch()} /> : <>{reviews.data.data.length ? reviews.data.data.map(r=><ReviewCard key={r.id} review={r}>{admin && <ResponseForm key={r.responseUpdatedAt || "new"} review={r} />}</ReviewCard>) : <p>Chưa có đánh giá</p>}<Pagination pagination={reviews.data.pagination} onPage={setPage} /></>}</section></div>;
}
