-- Operational maintenance; no financial or live odometer domain.
CREATE TABLE bus_maintenance_records (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 bus_id BIGINT NOT NULL,
 maintenance_type VARCHAR(30) NOT NULL,
 status VARCHAR(30) NOT NULL,
 title VARCHAR(150) NOT NULL,
 note VARCHAR(1000) NULL,
 scheduled_start DATETIME(6) NOT NULL,
 scheduled_end DATETIME(6) NOT NULL,
 started_at DATETIME(6) NULL,
 completed_at DATETIME(6) NULL,
 cancelled_at DATETIME(6) NULL,
 odometer_km BIGINT NULL,
 next_due_date DATE NULL,
 next_due_odometer_km BIGINT NULL,
 previous_bus_status VARCHAR(30) NULL,
 created_by BIGINT NOT NULL,
 completed_by BIGINT NULL,
 cancelled_by BIGINT NULL,
 completion_note VARCHAR(1000) NULL,
 cancellation_reason VARCHAR(500) NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 INDEX idx_maintenance_bus_status_start (bus_id,status,scheduled_start),
 INDEX idx_maintenance_status_start (status,scheduled_start),
 INDEX idx_maintenance_bus_completed (bus_id,status,completed_at,id),
 FOREIGN KEY (bus_id) REFERENCES buses(id),
 FOREIGN KEY (created_by) REFERENCES users(id),
 FOREIGN KEY (completed_by) REFERENCES users(id),
 FOREIGN KEY (cancelled_by) REFERENCES users(id),
 CHECK (scheduled_end > scheduled_start),
 CHECK (status IN ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED')),
 CHECK (maintenance_type IN ('PERIODIC_SERVICE','OIL_CHANGE','TIRE','BRAKE','ELECTRICAL','ENGINE','AIR_CONDITIONING','INSPECTION','REPAIR','OTHER')),
 CHECK (odometer_km IS NULL OR odometer_km >= 0),
 CHECK (next_due_odometer_km IS NULL OR next_due_odometer_km >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bus_status_history (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 bus_id BIGINT NOT NULL,
 previous_status VARCHAR(30) NOT NULL,
 new_status VARCHAR(30) NOT NULL,
 reason_code VARCHAR(50) NOT NULL,
 maintenance_id BIGINT NULL,
 changed_by BIGINT NOT NULL,
 changed_at DATETIME(6) NOT NULL,
 INDEX idx_bus_status_history_bus_changed (bus_id,changed_at,id),
 FOREIGN KEY (bus_id) REFERENCES buses(id),
 FOREIGN KEY (maintenance_id) REFERENCES bus_maintenance_records(id),
 FOREIGN KEY (changed_by) REFERENCES users(id),
 CHECK (previous_status IN ('AVAILABLE','MAINTENANCE','INACTIVE')),
 CHECK (new_status IN ('AVAILABLE','MAINTENANCE','INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
