import { DomainStatusBadge } from "../../components/DomainStatusBadge";
import { Loading } from "../../components/ui";
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { canManageOperator } from '../auth/access';
import { fleetApi } from '../../api/fleetApi';
import { allPages, operatorApi } from '../../api/operatorApi';
import type { BusResponse } from '../../types/operator';
import type { FleetReadiness, Maintenance, MaintenanceStatus, MaintenanceType } from '../../types/fleet';
import { date, dateTime } from '../../utils/format';
import { OperatorError, OperatorPageHeader, OperatorStatusBadge, OperatorTable, Pagination, QueryState, useOperatorFilters } from './shared';
import { maintenanceActions, maintenanceTypes, maintenanceStatuses, validMaintenanceWindow, vietnamTimestamp } from './fleet';
import './fleet.css';

export function ReadinessBadge({readiness}:{readiness?:FleetReadiness}) {
  return <span className={`operator-badge ${readiness?.operationalReady?'operator-status-AVAILABLE':'operator-status-INACTIVE'}`}>{readiness ? readiness.operationalReady?'Sẵn sàng':'Chưa sẵn sàng':'Chưa có dữ liệu'}</span>;
}
export function BusReadiness({readiness,compact=false}:{readiness?:FleetReadiness;compact?:boolean}) {
  if(!readiness) return <p className="fine-print">Chưa có dữ liệu sẵn sàng.</p>;
  return <div className="fleet-readiness">{!compact && <ReadinessBadge readiness={readiness}/>}
    {readiness.warnings.length > 0 && <div className="fleet-warning-strip">{readiness.warnings.map(w=><p key={w}>{w}</p>)}</div>}
    <dl className="fleet-operational-blocks">
      <div className={readiness.nextMaintenanceDate ? 'fleet-maintenance-next' : 'fleet-quiet'}><dt>{readiness.nextMaintenanceDate ? 'Bảo trì tiếp theo' : 'Bảo trì'}</dt><dd>{readiness.nextMaintenanceDate ? <><strong>{dateTime(readiness.nextMaintenanceDate)}</strong><span>{maintenanceTypes[readiness.nextMaintenanceType!]}</span></> : maintenanceStatuses[readiness.maintenanceState as MaintenanceStatus] || 'Chưa có lịch'}</dd></div>
      <div className={readiness.nextAssignedTrip ? '' : 'fleet-quiet'}><dt>Chuyến tiếp theo</dt><dd>{readiness.nextAssignedTrip ? <Link to={`/operator/trips/${readiness.nextAssignedTrip.id}`}><strong>{readiness.nextAssignedTrip.route}</strong><span>{dateTime(readiness.nextAssignedTrip.departureTime)}</span></Link> : 'Chưa phân công'}</dd></div>
    </dl><p className="fleet-due">Hạn bảo dưỡng: {readiness.nextDueDate ? date(readiness.nextDueDate) : 'Chưa ghi nhận'}</p>
  </div>;
}
export function FleetDirectoryContent({buses}:{buses:BusResponse[]}) {
  return <><div className="fleet-desktop"><OperatorTable headers={['Biển số','Loại xe / ghế','Sẵn sàng','Bảo trì / chuyến tiếp theo','Thao tác']} empty={!buses.length}>{buses.map(b=><tr key={b.id}><td><Link className="fleet-plate" to={`/operator/buses/${b.id}`}>{b.licensePlate}</Link></td><td>{b.busType.name}<span className="fleet-capacity">{b.busType.seatCount} ghế</span></td><td><ReadinessBadge readiness={b.readiness}/>{b.status !== "AVAILABLE" && <p className="fine-print">Trạng thái xe: <OperatorStatusBadge status={b.status}/></p>}</td><td><BusReadiness readiness={b.readiness} compact/></td><td><Link className="button secondary" to={`/operator/buses/${b.id}`}>Xem xe</Link></td></tr>)}</OperatorTable></div><div className="fleet-mobile">{buses.map(b=><article className="card" key={b.id}><h2><Link className="fleet-plate" to={`/operator/buses/${b.id}`}>{b.licensePlate}</Link></h2><p className="fleet-capacity">{b.busType.name} · {b.busType.seatCount} ghế</p>{b.status !== "AVAILABLE" && <p className="fine-print">Trạng thái xe: <OperatorStatusBadge status={b.status}/></p>}<BusReadiness readiness={b.readiness}/><Link className="button secondary" to={`/operator/buses/${b.id}`}>Xem xe</Link></article>)}</div></>;
}
function MaintenanceError({error}:{error:unknown}) {
  const trips=(error as {response?:{data?:{details?:{trips?:{id:number;route:string;departureTime:string;status:string}[]}}}})?.response?.data?.details?.trips;
  return <><OperatorError error={error}/>{trips?.map(t=><p className="notice warning" key={t.id}><Link to={`/operator/trips/${t.id}`}>Chuyến #{t.id} · {t.route}</Link> · {dateTime(t.departureTime)} · <OperatorStatusBadge status={t.status}/></p>)}</>;
}
export function MaintenanceScheduleForm({busId,onSubmit,pending=false}:{busId:number; onSubmit:(input:Parameters<typeof fleetApi.schedule>[1])=>void; pending?:boolean}) {
  const [error,setError]=useState('');
  return <form className="card form-stack fleet-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const start=String(f.get('start'));const end=String(f.get('end'));if(!validMaintenanceWindow(start,end)){setError('Thời gian kết thúc phải sau thời gian bắt đầu.');return;}setError('');onSubmit({maintenanceType:f.get('type') as MaintenanceType,title:String(f.get('title')).trim(),note:String(f.get('note')||'').trim(),scheduledStart:vietnamTimestamp(start),scheduledEnd:vietnamTimestamp(end)});}}><h3>Lên lịch bảo trì</h3><p>Giờ Việt Nam · Chỉ ghi thông tin vận hành, tránh thông tin cá nhân nhạy cảm.</p><fieldset disabled={pending || !busId}><label className="field">Loại bảo trì<select aria-label="Loại bảo trì" name="type">{Object.entries(maintenanceTypes).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field">Tiêu đề<input name="title" required maxLength={150}/></label><label className="field">Bắt đầu<input name="start" type="datetime-local" required/></label><label className="field">Kết thúc<input name="end" type="datetime-local" required/></label><label className="field">Ghi chú<textarea name="note" maxLength={1000}/></label><button>{pending?'Đang lưu…':'Tạo lịch bảo trì'}</button></fieldset>{error && <p role="alert">{error}</p>}</form>;
}
function MaintenanceActions({record}:{record:Maintenance}) {
  const cache=useQueryClient();const [action,setAction]=useState<string|null>(null);
  const mutation=useMutation({mutationFn:(f:FormData)=>action==='start'?fleetApi.start(record.id):action==='cancel'?fleetApi.cancel(record.id,String(f.get('reason')||'').trim()):fleetApi.complete(record.id,{odometerKm:f.get('odometer')?Number(f.get('odometer')):undefined,nextDueDate:String(f.get('due')||'')||undefined,nextDueOdometerKm:f.get('nextOdometer')?Number(f.get('nextOdometer')):undefined,note:String(f.get('note')||'').trim()}),onSuccess:async()=>{setAction(null);await cache.invalidateQueries({queryKey:['operator']});}});
  return <div className="fleet-actions">{!action ? maintenanceActions(record.status,true).map(a=><button key={a} className={a==='cancel'?'secondary':undefined} onClick={()=>{mutation.reset();setAction(a);}}>{a==='start'?'Bắt đầu':a==='complete'?'Hoàn tất':'Hủy kế hoạch'}</button>):<form className="form-stack" onSubmit={e=>{e.preventDefault();mutation.mutate(new FormData(e.currentTarget));}}><fieldset disabled={mutation.isPending}><p>{action==='start'?'Bắt đầu bảo trì sẽ làm xe không sẵn sàng vận hành.':action==='cancel'?'Hủy lịch và giữ lại lịch sử.':'Hoàn tất bảo trì; trạng thái xe được khôi phục theo trạng thái trước bảo trì.'}</p>{action==='cancel' && <label className="field">Lý do<input name="reason" maxLength={500}/></label>}{action==='complete' && <><label className="field">Số km ghi nhận (không đồng bộ thực tế)<input name="odometer" type="number" min={0} step={1}/></label><label className="field">Hạn bảo dưỡng tiếp theo<input name="due" type="date"/></label><label className="field">Số km bảo dưỡng tiếp theo<input name="nextOdometer" type="number" min={0} step={1}/></label><label className="field">Ghi chú hoàn tất<textarea name="note" maxLength={1000}/></label></>}<button disabled={mutation.isPending}>Xác nhận</button> <button type="button" className="secondary" onClick={()=>setAction(null)}>Quay lại</button></fieldset></form>}{mutation.isError && <MaintenanceError error={mutation.error}/>}</div>;
}
export function MaintenanceListContent({records,manage}:{records:Maintenance[];manage:boolean}) {
  return <div className="maintenance-list">{!records.length && <p className="notice info">Chưa có lịch bảo trì phù hợp.</p>}{records.map(m=><article key={m.id} className={`card maintenance-row ${["COMPLETED","CANCELLED"].includes(m.status) ? "maintenance-history" : ""}`}><div><h3>{dateTime(m.scheduledStart)} · <Link to={`/operator/buses/${m.busId}`}>{m.licensePlate}</Link></h3><p>{m.title}</p><p>{maintenanceTypes[m.maintenanceType]} · <DomainStatusBadge domain="maintenance" status={m.status} /></p><p>{dateTime(m.scheduledStart)} → {dateTime(m.scheduledEnd)}</p><details className="maintenance-record-details" open={["SCHEDULED","IN_PROGRESS"].includes(m.status)}><summary>Chi tiết bảo trì</summary>{m.note && <p>{m.note}</p>}{m.startedAt && <p>Bắt đầu: {dateTime(m.startedAt)}</p>}{m.completedAt && <p>Hoàn tất: {dateTime(m.completedAt)}</p>}{m.cancelledAt && <p>Đã hủy: {dateTime(m.cancelledAt)} · {m.cancellationReason}</p>}{m.completionNote && <p>{m.completionNote}</p>}{m.odometerKm!=null && <p>Số km ghi nhận: {m.odometerKm}</p>}{m.nextDueDate && <p>Hạn tiếp theo: {date(m.nextDueDate)}</p>}{m.nextDueOdometerKm!=null && <p>Số km bảo dưỡng tiếp theo: {m.nextDueOdometerKm}</p>}</details></div>{manage && <MaintenanceActions record={m}/>}</article>)}</div>;
}
export function MaintenanceWorkspace({busId}:{busId?:number}) {
  const {params,page,size,set}=useOperatorFilters();
  const filters={busId:busId || Number(params.get('busId')) || undefined,status:(params.get('status')||undefined) as MaintenanceStatus|undefined,maintenanceType:(params.get('maintenanceType')||undefined) as MaintenanceType|undefined,fromDate:params.get('fromDate')||undefined,toDate:params.get('toDate')||undefined,page,size};
  const query=useQuery({queryKey:['operator','maintenance',filters],queryFn:({signal})=>fleetApi.maintenance(filters,signal)});
  const buses=useQuery({queryKey:['operator','buses','maintenance-options'],queryFn:({signal})=>allPages(p=>operatorApi.buses(p,signal)),enabled:!busId});
  const [selected,setSelected]=useState(busId||0);const [create,setCreate]=useState(false);const cache=useQueryClient();
  const schedule=useMutation({mutationFn:(input:Parameters<typeof fleetApi.schedule>[1])=>fleetApi.schedule(busId||selected,input),onSuccess:async()=>{setCreate(false);await cache.invalidateQueries({queryKey:['operator']});}});
  return <>{!busId && buses.isPending && <Loading />}{!busId && buses.isError && <OperatorError error={buses.error} retry={()=>void buses.refetch()} />}<div className="operator-actions"><button onClick={()=>{schedule.reset();setCreate(!create);}}>{create?'Đóng biểu mẫu':'Lên lịch bảo trì'}</button></div>{create && <>{!busId && <label className="field">Xe<select aria-label="Xe" value={selected} onChange={e=>setSelected(Number(e.target.value))}><option value={0}>Chọn xe</option>{buses.data?.map(b=><option key={b.id} value={b.id}>{b.licensePlate}</option>)}</select></label>}<MaintenanceScheduleForm busId={busId||selected} onSubmit={input=>schedule.mutate(input)} pending={schedule.isPending}/>{schedule.isError && <MaintenanceError error={schedule.error}/>}</>}<nav className="quick-filters" aria-label="Lọc bảo trì">{[["", "Tất cả"], ["SCHEDULED", "Đã lên lịch"], ["IN_PROGRESS", "Đang bảo trì"], ["COMPLETED", "Hoàn tất"], ["CANCELLED", "Đã hủy"]].map(([value,label]) => <button key={value} className="secondary" aria-pressed={(filters.status || "") === value} onClick={() => set("status", value)}>{label}</button>)}</nav><div className="operator-filters">{!busId && <label className="field">Xe<select aria-label="Xe" value={filters.busId||''} onChange={e=>set('busId',e.target.value)}><option value="">Tất cả</option>{buses.data?.map(b=><option value={b.id} key={b.id}>{b.licensePlate}</option>)}</select></label>}<label className="field">Trạng thái<select aria-label="Trạng thái" value={filters.status||''} onChange={e=>set('status',e.target.value)}><option value="">Tất cả</option>{Object.entries(maintenanceStatuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field">Loại bảo trì<select aria-label="Loại bảo trì" value={filters.maintenanceType||''} onChange={e=>set('maintenanceType',e.target.value)}><option value="">Tất cả</option>{Object.entries(maintenanceTypes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field">Từ ngày<input type="date" value={filters.fromDate||''} onChange={e=>set('fromDate',e.target.value)}/></label><label className="field">Đến ngày<input type="date" value={filters.toDate||''} onChange={e=>set('toDate',e.target.value)}/></label></div><p className="fine-print">Ngày bảo trì theo lịch Việt Nam. Giờ hiển thị theo Việt Nam (UTC+7).</p><QueryState query={query}>{d=><><MaintenanceListContent records={d.data} manage/><Pagination pagination={d.pagination} set={set}/></>}</QueryState></>;
}
export function OperatorMaintenancePage() {
  return canManageOperator(useAuth().user?.roles)?<><OperatorPageHeader title="Bảo trì đội xe"><Link to="/operator/buses">Đội xe</Link></OperatorPageHeader><MaintenanceWorkspace/></>:<p role="alert">Bạn không có quyền xem đội xe.</p>;
}
export function BusFleetWorkspace({bus,overview}:{bus:BusResponse;overview:React.ReactNode}) {
  const [tab,setTab]=useState('Tổng quan');const [page,setPage]=useState(0);
  const trips=useQuery({queryKey:['operator','fleet-trips',bus.id,page],queryFn:({signal})=>fleetApi.trips(bus.id,page,signal),enabled:tab==='Lịch chuyến'});
  const history=useQuery({queryKey:['operator','fleet-history',bus.id],queryFn:({signal})=>fleetApi.history(bus.id,signal),enabled:tab==='Lịch sử'});
  return <><nav className="fleet-tabs" aria-label="Không gian đội xe">{['Tổng quan','Lịch chuyến','Bảo trì','Lịch sử'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>{tab==='Tổng quan' && <><BusReadiness readiness={bus.readiness}/>{overview}</>}{tab==='Bảo trì' && <MaintenanceWorkspace busId={bus.id}/>} {tab==='Lịch chuyến' && <QueryState query={trips}>{d=><><OperatorTable headers={['Chuyến / tuyến','Khởi hành','Đến dự kiến','Trạng thái']} empty={!d.data.length}>{d.data.map(t=><tr key={t.id}><td><Link to={`/operator/trips/${t.id}`}>#{t.id} · {t.route}</Link></td><td>{dateTime(t.departureTime)}</td><td>{dateTime(t.estimatedArrivalTime)}</td><td><OperatorStatusBadge status={t.status}/></td></tr>)}</OperatorTable><Pagination pagination={d.pagination} set={(_,v)=>setPage(Number(v))}/></>}</QueryState>}{tab==='Lịch sử' && <QueryState query={history}>{rows=><><p>100 thay đổi trạng thái gần nhất. Phân công xe cố định khi tạo chuyến; không có đổi xe sau tạo.</p>{!rows.length && <p>Chưa có thay đổi trạng thái ghi nhận.</p>}{rows.map(h=><p className="card" key={h.id}>{dateTime(h.changedAt)} · <OperatorStatusBadge status={h.previousStatus}/> → <OperatorStatusBadge status={h.newStatus}/> · {h.reasonCode==='MAINTENANCE_STARTED'?'Bắt đầu bảo trì':h.reasonCode==='MAINTENANCE_COMPLETED'?'Hoàn tất bảo trì':'Điều chỉnh trạng thái'} · Người thực hiện #{h.changedBy}{h.maintenanceId && ` · Bảo trì #${h.maintenanceId}`}</p>)}</>}</QueryState>}</>;
}
export function FleetDashboardWarnings() {
  const query=useQuery({queryKey:['operator','fleet-warnings'],queryFn:({signal})=>fleetApi.warnings(signal),refetchInterval:60000});
  return <section className="card"><h2>Cảnh báo đội xe</h2><Link to="/operator/maintenance">Quản lý bảo trì</Link><QueryState query={query}>{d=><><p>Trạng thái xe · Sẵn sàng: {d.availableBuses} · Đang bảo trì: {d.maintenanceBuses} · Ngừng hoạt động: {d.inactiveBuses}</p><p>Bảo trì trong 7 ngày tới: {d.maintenanceDueSoon} · Quá hạn theo ngày: {d.overdueMaintenance}</p>{d.upcomingNotReady.map(t=><p className="notice warning" key={t.id}><Link to={`/operator/trips/${t.id}`}>Chuyến #{t.id} · {t.route}</Link> · {dateTime(t.departureTime)} · Xe chưa sẵn sàng hoặc trùng lịch bảo trì</p>)}</>}</QueryState></section>;
}
