import assert from 'node:assert/strict';
import { test } from 'node:test';
import { register } from 'node:module';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
register('./helpers/tsx-loader.mjs',import.meta.url);
const { ReportContent, OperatorReportsPage, reportPreset, reportPercent, reportLoadPercent }=await import('../src/features/operator/Reports.tsx');
const { AuthContext }=await import('../src/features/auth/AuthProvider.tsx');
const { operatorNavigation, canAccessOperatorPath }=await import('../src/features/auth/access.ts');
const zeroMoney={grossMockCollections:0,mockRefunds:0,netMockCollections:0,paidPaymentCount:0,refundedPaymentCount:0};
const base={metadata:{fromDate:'2026-10-03',toDate:'2026-10-03',timezone:'Asia/Ho_Chi_Minh',asOf:'2026-10-03T03:00:00Z'},collections:{totals:zeroMoney,byPaymentMethod:{MOCK_ONLINE:zeroMoney,QR_TRANSFER:zeroMoney,PAY_ON_BOARD:zeroMoney},trend:[{date:'2026-10-03',money:zeroMoney}]},bookings:{bookingsCreated:0,byStatus:{PENDING:0,CONFIRMED:0,CANCELLED:0,COMPLETED:0},bySource:{WEB:0,PHONE:0},cancellations:0,paymentTimeouts:0,currentUnpaidCount:0,ticketsIssued:0,validTickets:0,voidTickets:0},cancellations:{totalCancellations:0,byReason:{CUSTOMER_CANCELLED:0,OPERATOR_CANCELLED:0,PAYMENT_TIMEOUT:0},refundedCancellations:0,unpaidCancellations:0,amountRefunded:0},attendance:{eligibleResolvedTickets:0,boardedTickets:0,noShowTickets:0,checkedInNotBoarded:0,unresolvedAttendance:0,ticketlessNoShows:0,boardingRate:null,noShowRate:null},load:{expectedCells:0,actualCells:0,missingCells:0,sellableCells:0,reservedCells:0,paidCells:0,heldCells:0,complete:true,reservedSegmentLoad:null,paidSegmentLoad:null},operations:{trips:0,boardingTrips:0,runningTrips:0,upcomingWithoutDriver:0,openPickups:0,incompleteTrips:0}};
function render(report,tab) { return renderToStaticMarkup(React.createElement(ReportContent,{report,tab})); }
function page(roles,report) {
  const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
  if(report) client.setQueryData(['operator','reports','summary',reportPreset('today')],report);
  return renderToStaticMarkup(React.createElement(QueryClientProvider,{client},React.createElement(AuthContext.Provider,{value:{user:{roles},authenticated:true,loading:false}},React.createElement(MemoryRouter,null,React.createElement(OperatorReportsPage)))));
}
test('empty report retains known zero values and explicit transaction / departure basis',()=>{const html=render(base);assert.match(html,/Không có hoạt động/);assert.match(html,/ngày giao dịch/);assert.match(html,/ngày khởi hành/);assert.match(html,/ngày tạo/);assert.match(html,/Asia\/Ho_Chi_Minh/);});
test('populated collections and charts use simulated wording and all three payment methods',()=>{const html=render({...base,collections:{...base.collections,totals:{...zeroMoney,grossMockCollections:600000,mockRefunds:100000,netMockCollections:500000,paidPaymentCount:3}}});for(const method of ['MOCK_ONLINE','QR_TRANSFER','PAY_ON_BOARD']) assert.doesNotMatch(html,new RegExp(method));assert.match(html,/Tổng thu mô phỏng/);assert.match(html,/Hoàn tiền mô phỏng/);assert.match(html,/Thu ròng mô phỏng/);assert.doesNotMatch(html,/Doanh thu thực tế/);assert.match(html,/Biểu đồ tổng thu/);});
test('WEB PHONE status and ticket cohorts are separate from transported passengers',()=>{const html=render({...base,bookings:{...base.bookings,bookingsCreated:3,bySource:{WEB:1,PHONE:2},ticketsIssued:6,voidTickets:2}},'Đặt vé & vé');assert.match(html,/WEB/);assert.match(html,/PHONE/);assert.match(html,/Một booking nhiều ghế/);assert.match(html,/không xác nhận đã vận chuyển/);assert.match(html,/ngày hủy/);});
test('missing inventory suppresses load percentage and attendance without records is explicit',()=>{const html=render({...base,load:{...base.load,expectedCells:6,actualCells:5,missingCells:1,sellableCells:6,complete:false},attendance:{...base.attendance,unresolvedAttendance:3,ticketlessNoShows:1}});assert.match(html,/Dữ liệu ghế chưa đầy đủ/);assert.match(html,/thiếu 1 ô/);assert.match(html,/Chưa ghi nhận/);assert.match(html,/Vắng mặt chưa có vé/);assert.doesNotMatch(html,/Infinity|NaN/);});
test('range presets use inclusive Vietnam dates across month boundaries and empty rates are null',()=>{assert.deepEqual(reportPreset('7','2026-10-03'),{fromDate:'2026-09-27',toDate:'2026-10-03'});assert.deepEqual(reportPreset('month','2026-10-03'),{fromDate:'2026-10-01',toDate:'2026-10-03'});assert.equal(reportPercent(null),'Chưa đủ dữ liệu');});
test('load with no contributing capacity is not applicable while incomplete non-cancelled load stays unknown',()=>{const html=render(base,'Chuyến / Tuyến');assert.match(html,/Không áp dụng/);assert.match(html,/Chuyến đã hủy không góp vào tải tổng hợp/);assert.equal(reportLoadPercent({...base.load,complete:false},null),'Chưa đủ dữ liệu');assert.doesNotMatch(html,/0%/);});
test('admin reports show loading and shared filter bar',()=>{const html=page(['OPERATOR_ADMIN']);assert.match(html,/Đang tải báo cáo/);for(const label of ['Từ ngày','Đến ngày','Nguồn booking','Phương thức','Tuỳ chọn','Áp dụng'])assert.match(html,new RegExp(label));});
test('staff and system admins never mount report queries or see financial data',()=>{for(const roles of [['OPERATOR_STAFF'],['SYSTEM_ADMIN'],['OPERATOR_ADMIN','SYSTEM_ADMIN']]){const html=page(roles,base);assert.match(html,/không có quyền/);assert.doesNotMatch(html,/Tổng thu mô phỏng|MOCK_ONLINE|report-filters/);assert.equal(canAccessOperatorPath(roles,'/operator/reports'),false);assert.ok(!operatorNavigation(roles).some(([path])=>path==='/reports'));}assert.ok(operatorNavigation(['OPERATOR_ADMIN']).some(([path])=>path==='/reports'));});
